---
# tasks file for ferm

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags:
    - ferm
    - setup
    - config
    - service

# Debian specific tasks
- include: setup-Debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu')
  tags: [ferm, setup]

# CentOS  specific tasks
- include: setup-CentOS.yml
  when: ansible_distribution in ('CentOS', 'RedHat')
  tags: [ferm, setup]

# common setup tasks
- include: setup-common.yml
  tags: [ferm, setup]

- include: config.yml

- include: service.yml
