---
- name: "debian | install packages"
  action: apt name={{ item }} state={{ ferm_pkg_state|default('present') }}
  tags:
    - zabbix-agent
    - setup
  with_items: ferm_packages

- name: "debian | remove packages"
  action: apt name={{ item }} state=absent
  tags:
    - zabbix-agent
    - setup
  with_items: ferm_packages_remove

