---
# handlers file for ferm
- name: ferm generate rules
  command:
    ferm {{ferm_directory}}/ferm.conf
  notify:
    - ferm save rules ip4
    - ferm save rules ip6
  when: not ferm_test

- name: ferm save rules ip4
  command:
    service iptables save
  when: "'ip' in ferm_domains and ansible_distribution in ('CentOS', 'RedHat')"
  args:
    warn: false

- name: ferm save rules ip6
  command:
    service ip6tables save
  when: "'ip6' in ferm_domains and ansible_distribution in ('CentOS', 'RedHat')"
  args:
    warn: false
